name: flutter_widget_recorder_example
description: "Demonstrates how to use the flutter_widget_recorder plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_widget_recorder:
    path: ../

  cupertino_icons: ^1.0.8

  # For sharing the video
  share_plus: ^10.1.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
