name: flutter_widget_recorder
description:
  "A Flutter plugin for recording widget animation using RepaintBoundary
  widget and sending it to the platform plugin for conversion to video"
version: 0.0.2
homepage: https://github.com/RuslanTsitser/flutter_widget_recorder
repository: https://github.com/RuslanTsitser/flutter_widget_recorder
issue_tracker: https://github.com/RuslanTsitser/flutter_widget_recorder/issues
documentation: https://github.com/RuslanTsitser/flutter_widget_recorder/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterWidgetRecorderPlugin
      android:
        package: com.tsitser.flutter_widget_recorder
        pluginClass: FlutterWidgetRecorderPlugin
